# This is a basic workflow to help you get started with Actions

name: testing actions

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Set GITHUB_VARIABLE
        run: echo "RELEASE_VERSION=$(date +"%Y%m%d")" >> "$GITHUB_ENV"
      - name: check ${{env.RELEASE_VERSION}}
        run: env
