name: MariaDB Dumper
on:
#  schedule:
#    - cron: "* */48 * * *"
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: run-dev
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ["6.0"]

    steps:
      - name: Git checkout GHSAdumper
        uses: actions/checkout@v3

      - name: Install mariadb
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg mariadb-server
          mysql -u root -e "SHOW DATABASES"
