name: MongoDB Dumper test action
on:
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: run-dev
  cancel-in-progress: true

jobs:
  import_export:
    name: Initial Import Export
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout GHSAdumper
        uses: actions/checkout@v3

      - name: Install mongo tools command
        run: |
          echo "RELEASE_VERSION=$(date +"%Y%m%d")" >> "$GITHUB_ENV"
          sudo apt-get update
          sudo apt-get install -y wget gnupg docker-compose
          wget -qO - https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
      - name: Download the advisories zip file
        run: |
          wget -q https://github.com/github/advisory-database/archive/refs/heads/main.zip
          unzip -q main.zip
          rm main.zip

      - name: start docker services
        run: |
          docker ps
          docker-compose -f maxscale-compose.yml up -d
          sudo mkdir -p /data/db
          sudo mongod --fork --syslog
          sleep 5
